services:

  watchtower:
    image: nickfedor/watchtower:1
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    command:
      - "--cleanup"
      - "--interval"
      - "300"
      - "--rolling-restart"
      - "--notifications"
      - "email"
    security_opt:
      - no-new-privileges:true


  redis:
    image: redis:8-alpine3.21
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true

  web:
    image: andreastuko/esc:latest
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    command: ["./build.sh"]
    ports:
      - "127.0.0.1:8000:8000"  # Only bind to localhost for security

    volumes:
      - logs_data:/app/logs
      - geoip:/app/geoip
    healthcheck:
      test: ["CMD", "python3", "./docker-health-check.py"]
      interval: 30s
      timeout: 120s
      retries: 5
      start_period: 240s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  celery_worker:
    image: andreastuko/esc:latest
    restart: unless-stopped
    command: >
      celery -A esc worker
      --loglevel=info
      --concurrency=2
      --prefetch-multiplier=1
    env_file:
      - .env.docker
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - logs_data:/app/logs
      - geoip:/app/geoip
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A esc inspect ping -d celery@$${HOSTNAME} || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  celery_beat:
    image: andreastuko/esc:latest
    restart: unless-stopped
    command: celery -A esc beat -l info
    env_file:
      - .env.docker
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_healthy
    volumes:
      - logs_data:/app/logs
      - geoip:/app/geoip
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  redis_data:
  logs_data:
  geoip:


# docker pull andreastuko/esc:latest && docker compose -f compose.prod.yaml up
 
